# .github/workflows/build.yml
name: Build Runner

on:
  push:
    branches: ["main"]
    paths:
      - 'DataSDI/**'
  pull_request:
    branches: ["main"]
    
env:
  SCHEME: DataSDI # Pastikan ini adalah nama skema macOS Anda

jobs:
  build:
    runs-on: macos-14 # Disarankan menggunakan runner macOS terbaru
    steps:
      - uses: actions/checkout@v4 # Gunakan versi terbaru dari actions/checkout

      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0' # Pastikan versi Xcode yang Anda inginkan tersedia di runner macos-14

      - name: Build macOS
        run: xcodebuild -scheme "$SCHEME" -derivedDataPath .build -destination 'generic/platform=OS X' # Menggunakan SCHEME dari env
