# .github/workflows/release.yml
name: Release Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump (major, minor, patch) - applies to build number only for now'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      target_scheme:
        description: 'Xcode Scheme to get Info.plist from'
        required: true
        default: 'Data SDI' # Ganti dengan skema utama Anda

jobs:
  create-version:
    runs-on: macos-14
    permissions:
      contents: write # Diperlukan untuk git commit, tag, dan push
    if: github.ref == 'refs/heads/main' # Pastikan hanya berjalan di main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Penting untuk operasi git (tagging, commit, push)

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'

      - name: Get Info.plist path and Current Version
        id: get_version
        run: |
          # Temukan jalur Info.plist untuk skema yang ditentukan
          # Ini adalah contoh umum, sesuaikan jika Info.plist Anda ada di lokasi yang tidak biasa
          # Biasanya di bawah direktori proyek utama Anda.
          INFO_PLIST_PATH=$(find . -name "Info.plist" -not -path "./Pods/*" -print -quit)

          if [ -z "$INFO_PLIST_PATH" ]; then
            echo "Error: Info.plist not found for scheme ${{ github.event.inputs.target_scheme }}"
            exit 1
          fi
          
          # Ambil Build Number (CFBundleVersion)
          CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST_PATH")
          
          # Ambil Marketing Version (CFBundleShortVersionString)
          CURRENT_MARKETING_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST_PATH")

          echo "Current Build Number: $CURRENT_BUILD_NUMBER"
          echo "Current Marketing Version: $CURRENT_MARKETING_VERSION"
          echo "INFO_PLIST_PATH=$INFO_PLIST_PATH" >> "$GITHUB_OUTPUT"
          echo "CURRENT_BUILD_NUMBER=$CURRENT_BUILD_NUMBER" >> "$GITHUB_OUTPUT"
          echo "CURRENT_MARKETING_VERSION=$CURRENT_MARKETING_VERSION" >> "$GITHUB_OUTPUT"

      - name: Bump Build Number
        id: bump_build
        run: |
          INFO_PLIST_PATH="${{ steps.get_version.outputs.INFO_PLIST_PATH }}"
          CURRENT_BUILD_NUMBER="${{ steps.get_version.outputs.CURRENT_BUILD_NUMBER }}"
          NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
          
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$INFO_PLIST_PATH"
          echo "Bumped CFBundleVersion to $NEW_BUILD_NUMBER in $INFO_PLIST_PATH"
          echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Commit, Tag, and Push Version Changes
        run: |
          CURRENT_MARKETING_VERSION="${{ steps.get_version.outputs.CURRENT_MARKETING_VERSION }}"
          NEW_BUILD_NUMBER="${{ steps.bump_build.outputs.NEW_BUILD_NUMBER }}"
          
          git add . # Tambahkan semua perubahan, termasuk Info.plist yang dimodifikasi
          git commit -m "Bump to v$CURRENT_MARKETING_VERSION (build $NEW_BUILD_NUMBER) [skip ci]" # [skip ci] untuk menghindari loop
          
          # Gunakan Marketing Version sebagai tag
          git tag "v$CURRENT_MARKETING_VERSION-build-$NEW_BUILD_NUMBER" # Contoh tag lebih detail
          # Atau jika Anda hanya ingin tag Marketing Version saja
          # git tag "v$CURRENT_MARKETING_VERSION"

          git push
          git push --tags
