# .github/workflows/release.yml
name: Release and Validate
on:
  push:
    tags:
      - "v*"
      - "V*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      # Checkout dengan ref yang benar
      - uses: actions/checkout@v4
        with:
          # Jika manual trigger, gunakan tag dari input
          # Jika push tag, gunakan ref default
          ref: ${{ github.event.inputs.tag || github.ref }}
          fetch-depth: 0

      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2.0"

      # Tentukan tag name yang akan digunakan
      - name: Set Tag Name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Set Release Product Name
        id: vars
        run: echo "PRODUCT_NAME=Data-SDI" >> $GITHUB_OUTPUT

      # Debug: Lihat commit yang sedang di-build
      - name: Show Current Commit
        run: |
          echo "Building from commit:"
          git log -1 --oneline
          echo "Tag being processed: ${{ steps.tag.outputs.TAG_NAME }}"

      - name: Build archive
        run: |
          xcodebuild archive \
            -scheme DataSDI \
            -archivePath "build/DataSDI.xcarchive" \
            -configuration Release \
            -destination "generic/platform=macOS"

      - name: Extract .app and Zip
        run: |
          mkdir -p build/app_staging
          cp -R "build/DataSDI.xcarchive/Products/Applications/Data SDI.app" "build/app_staging/"
          cd build/app_staging
          ZIP_NAME="${{ steps.vars.outputs.PRODUCT_NAME }}-${{ steps.tag.outputs.TAG_NAME }}.zip"
          zip -r "../${ZIP_NAME}" "Data SDI.app"

      # Upload ke Release (untuk push tag ATAU manual trigger)
      - name: Upload Official Release Asset
        # Jalankan jika: push tag ATAU manual trigger
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          files: build/${{ steps.vars.outputs.PRODUCT_NAME }}-${{ steps.tag.outputs.TAG_NAME }}.zip
          # Buat release jika belum ada
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Artifact hanya untuk testing (tidak ada tag)
      - name: Upload Build Artifact for Testing
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.event_name != 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.PRODUCT_NAME }}-Main-Build
          path: build/*.zip